### ISSUE TITLE
无法通过movieDb获取元数据

### ISSUE THREAD

**Issue by wdcew** [YukiCoco/EmbyCrack#4]
因为movieDbAPI域名好像被污染了，无法正确解析，只有通过修改host来正确解析ip地址。可是我在docker里面修改了hosts，依然无法获取元数据，使用正常版的emby通过修改hosts是可以正常通过movieDb获取电影的元数据的，不知道是什么原因呢？

**Comment by YukiCoco** [comment]
你进入 wget movieDbAPI的域名 看看通不通

**Comment by wdcew** [comment]
修改过HOST后，使用wget 可以正确获取数据，也能ping的通，movieAPI 的网址是 api.themoviedb.org。但是还是无法获取元数据

**Comment by YukiCoco** [comment]
查看后台的日志，贴出来。

**Comment by wdcew** [comment]
```
2020-07-28 02:33:56.061 Info HttpClient: GET https://api.themoviedb.org/3/movie/tt7286456?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=casts,releases,images,keywords,trailers&language=zh-CN&include_image_language=zh-CN,zh,null,en
2020-07-28 02:33:56.096 Error HttpClient: Error getting response from https://api.themoviedb.org/3/movie/tt7286456?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=casts,releases,images,keywords,trailers&language=zh-CN&include_image_language=zh-CN,zh,null,en
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.19.94.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: Network is unreachable
	 ---> System.Net.Sockets.SocketException (101): Network is unreachable
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.Net.Sockets.SocketException: Network is unreachable
	Source: System.Private.CoreLib
	TargetSite: Void Throw()
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	
2020-07-28 02:33:56.100 Error App: Error in TheMovieDb
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.19.94.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: Network is unreachable
	 ---> System.Net.Sockets.SocketException (101): Network is unreachable
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MovieDb.MovieDbProvider.GetMovieDbResponse(HttpRequestOptions options)
	   at MovieDb.MovieDbProvider.FetchMainResult(String id, Boolean isTmdbId, String language, String country, CancellationToken cancellationToken)
	   at MovieDb.GenericMovieDbInfo`1.FetchMovieData(String tmdbId, String imdbId, String language, String preferredCountryCode, CancellationToken cancellationToken)
	   at MovieDb.GenericMovieDbInfo`1.GetMetadata(ItemLookupInfo itemId, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.Net.Sockets.SocketException: Network is unreachable
	Source: System.Private.CoreLib
	TargetSite: Void Throw()
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	
2020-07-28 02:33:56.360 Info HttpClient: GET https://api.themoviedb.org/3/movie/tt7286456?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=casts,releases,images,keywords,trailers
2020-07-28 02:33:56.426 Error HttpClient: Error getting response from https://api.themoviedb.org/3/movie/tt7286456?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=casts,releases,images,keywords,trailers
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.19.94.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: Network is unreachable
	 ---> System.Net.Sockets.SocketException (101): Network is unreachable
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.Net.Sockets.SocketException: Network is unreachable
	Source: System.Private.CoreLib
	TargetSite: Void Throw()
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	
2020-07-28 02:33:56.429 Error ProviderManager: MovieDbImageProvider failed in GetImageInfos for type Movie
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.19.94.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: Network is unreachable
	 ---> System.Net.Sockets.SocketException (101): Network is unreachable
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at MovieDb.MovieDbProvider.GetMovieDbResponse(HttpRequestOptions options)
	   at MovieDb.MovieDbProvider.FetchMainResult(String id, Boolean isTmdbId, String language, String country, CancellationToken cancellationToken)
	   at MovieDb.MovieDbImageProvider.FetchImages(BaseItem item, String language, String preferredMetadataCountry, IJsonSerializer jsonSerializer, CancellationToken cancellationToken)
	   at MovieDb.MovieDbImageProvider.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken cancellationToken, IRemoteImageProvider provider, Int32 providerIndex)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.Net.Sockets.SocketException: Network is unreachable
	Source: System.Private.CoreLib
	TargetSite: Void Throw()
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	
2020-07-28 02:33:56.529 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/movies/movie/肖申克的救赎The.Shawshank.Redemption.1994.BluRay.1080p.x265.10bit.5Audio.MNHD-FRDS/The.Shawshank.Redemption.1994.BluRay.1080p.x265.10bit.5Audio.MNHD-FRDS.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2020-07-28 02:33:56.617 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0
2020-07-28 02:33:56.659 Info HttpClient: GET https://api.themoviedb.org/3/movie/tt0111161?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=casts,releases,images,keywords,trailers&language=zh-CN&include_image_language=zh-CN,zh,null,en
2020-07-28 02:33:56.716 Error HttpClient: Error getting response from https://api.themoviedb.org/3/movie/tt0111161?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=casts,releases,images,keywords,trailers&language=zh-CN&include_image_language=zh-CN,zh,null,en
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.19.94.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: Network is unreachable
	 ---> System.Net.Sockets.SocketException (101): Network is unreachable
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	Source: System.Net.Http
	TargetSite: Void MoveNext()
	InnerException: System.Net.Sockets.SocketException: Network is unreachable
	Source: System.Private.CoreLib
	TargetSite: Void Throw()
	   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

**Comment by YukiCoco** [comment]
现已决定内置加速刮削器
